### ISSUE TITLE
skip/skipLatest are messed up

### ISSUE THREAD

**Issue by machty** [staltz/rxmarbles#6] opened 2015-01-10 23:41 UTC
Wish I could provide a better description of the error but here's a visual:

![skip/skipLatest](http://g.recordit.co/vfFSIl7CeZ.gif)

It seems fine when refreshed, but if you navigate elsewhere and come back, it gets screwed up and displays some other result (not sure what).

**Comment by kolree** [comment] 2015-01-11 05:40
I am seeing this same issue - related to the problem with the diagram for "First" I tweeted you about. This seems to be a more general issue with the refresh somehow. To reproduce:
1. view Pausable Buffered
2. now try and view other diagrams - the results row seems to be stuck on the results from Pausable Buffered
I am using Safari 8.0.2 on OS X 10.10.1. I also see the same behavior on IE 11 on my Windows 7 VM.

**Comment by staltz** [comment] 2015-01-11 10:29
Thanks guys, this is a known issues. I am in the process of migrating RxMarbles to Cycle.js, and that will fix a number of issues. This issue here will be fixed by using the new [`withLatestFrom`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/withlatestfrom.md) in these lines: https://github.com/staltz/rxmarbles/blob/master/src/models/sandbox-output.js#L83

**Comment by staltz** [comment] 2015-01-30 18:06
Fixed in v1.2.1

**Closed by staltz** 2015-01-30 18:06 UTC
